# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chatgpt < Formula
  desc "A simple terminal UI for ChatGPT, written in Go with the tview library."
  homepage "https://github.com/quantonganh/chatgpt"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/chatgpt/releases/download/v0.0.5/chatgpt_Darwin_x86_64.tar.gz"
      sha256 "def765187109f975225f27a4c3fea6c5851d854a53dc3fa0392faa6442db540a"

      def install
        bin.install "chatgpt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quantonganh/chatgpt/releases/download/v0.0.5/chatgpt_Darwin_arm64.tar.gz"
      sha256 "bcc9e757ad7042c94cb93d31ca1b8789f3445a645b8c0e480c59f3e3f8f2ddc5"

      def install
        bin.install "chatgpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantonganh/chatgpt/releases/download/v0.0.5/chatgpt_Linux_arm64.tar.gz"
      sha256 "4c493075a4ca39b7f83ae0d38a82e39cd1a365f0864142e300d5e1c94ab1941a"

      def install
        bin.install "chatgpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/chatgpt/releases/download/v0.0.5/chatgpt_Linux_x86_64.tar.gz"
      sha256 "64f8e4872410f01e488553780e979f38ca4a25018a633deaed8b8e9b5d4006d1"

      def install
        bin.install "chatgpt"
      end
    end
  end
end
