# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chatgpt < Formula
  desc "A simple terminal UI for ChatGPT, written in Go with the tview library."
  homepage "https://github.com/quantonganh/chatgpt"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/chatgpt/releases/download/v0.0.3/chatgpt_Darwin_x86_64.tar.gz"
      sha256 "8cbb61e574bb19870de7290a9a351b911b594d7e66c0b087f053c6202053730c"

      def install
        bin.install "chatgpt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quantonganh/chatgpt/releases/download/v0.0.3/chatgpt_Darwin_arm64.tar.gz"
      sha256 "7d8c722f1e60477e7ef1645fa5d5c42fdb45690b5c44c2fc20ab987e4e0348f8"

      def install
        bin.install "chatgpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantonganh/chatgpt/releases/download/v0.0.3/chatgpt_Linux_arm64.tar.gz"
      sha256 "050a36d48e0318d638ee69a876c1852686b467abf4486ccdd17a830000f33597"

      def install
        bin.install "chatgpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/chatgpt/releases/download/v0.0.3/chatgpt_Linux_x86_64.tar.gz"
      sha256 "845e70c76521f862f73be11b82e572b8bcafc02b8005e26813401f42c5c9432d"

      def install
        bin.install "chatgpt"
      end
    end
  end
end
