# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChatgptTui < Formula
  desc "A simple terminal UI for ChatGPT, written in Go with the tview library."
  homepage "https://github.com/quantonganh/chatgpt"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/quantonganh/chatgpt-tui/releases/download/v0.0.6/chatgpt-tui_Darwin_arm64.tar.gz"
      sha256 "732fb2d20209d18590912ea92684581d2f91eb034ecdd3461878982fb8c3ec7d"

      def install
        bin.install "chatgpt-tui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/chatgpt-tui/releases/download/v0.0.6/chatgpt-tui_Darwin_x86_64.tar.gz"
      sha256 "5934a2e8c27d64e12bb03bc51c06b9319041743b430c779f95f7d8151dbc9ec6"

      def install
        bin.install "chatgpt-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantonganh/chatgpt-tui/releases/download/v0.0.6/chatgpt-tui_Linux_arm64.tar.gz"
      sha256 "3f674a5ecd790bad2be34a85735ff249ff153caf9e1e3cd742354490f4e906f6"

      def install
        bin.install "chatgpt-tui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/chatgpt-tui/releases/download/v0.0.6/chatgpt-tui_Linux_x86_64.tar.gz"
      sha256 "ae4d7845dd9b05e944dfaa3da37549f9a9c537e3fba0cc42b7e7a4ef1b169649"

      def install
        bin.install "chatgpt-tui"
      end
    end
  end
end
