# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chatgpt < Formula
  desc "A simple terminal UI for ChatGPT, written in Go with the tview library."
  homepage "https://github.com/quantonganh/chatgpt"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/quantonganh/chatgpt/releases/download/v0.0.4/chatgpt_Darwin_arm64.tar.gz"
      sha256 "55a9a3e516a6de644642e5fe577a8fa9b3a89b75d2506ba7685a3209c086f7bf"

      def install
        bin.install "chatgpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/chatgpt/releases/download/v0.0.4/chatgpt_Darwin_x86_64.tar.gz"
      sha256 "731fd76c7d7529e19a3f391b44852bb35a2a088290307e06f89ee697648c3321"

      def install
        bin.install "chatgpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantonganh/chatgpt/releases/download/v0.0.4/chatgpt_Linux_arm64.tar.gz"
      sha256 "d59aa85a00983a5a722dddd4cb55c23462601a0c03140d93485bd87666b2bbad"

      def install
        bin.install "chatgpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/chatgpt/releases/download/v0.0.4/chatgpt_Linux_x86_64.tar.gz"
      sha256 "e3508b103ac58d179b9f0c8fa3edbeed8fc8484b085a692a6c4d53d99eb27c77"

      def install
        bin.install "chatgpt"
      end
    end
  end
end
