# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelixWezterm < Formula
  desc "Turning Helix into an IDE with the help of WezTerm and CLI tools"
  homepage "https://github.com/quantonganh/helix-wezterm"
  version "0.0.1"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/quantonganh/helix-wezterm/releases/download/v0.0.1/helix-wezterm_Darwin_arm64.tar.gz"
      sha256 "46d3358b17e0099eb6f894036d4b287cb7b3c9fb6657e369ba11433fcf511f4f"

      def install
        bin.install "helix-fzf.sh"
        bin.install "helix-wezterm.sh"
      end
    end
  end
end
