# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelixWezterm < Formula
  desc "Turning Helix into an IDE with the help of WezTerm and CLI tools"
  homepage "https://github.com/quantonganh/helix-wezterm"
  version "0.0.1"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/quantonganh/helix-wezterm/releases/download/v0.0.1/helix-wezterm_Darwin_arm64.tar.gz"
      sha256 "26a857e1eca477a9910af62e0f279a1c5d6f4620615937149335fcdb4af64c02"

      def install
        bin.install "helix-fzf"
        bin.install "helix-wezterm"
      end
    end
  end
end
