# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelixWezterm < Formula
  desc "Turning Helix into an IDE with the help of WezTerm and CLI tools"
  homepage "https://github.com/quantonganh/helix-wezterm"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/helix-wezterm/releases/download/v0.0.1/helix-wezterm_Darwin_x86_64.tar.gz"
      sha256 "81cf1c796de2fc89e0b836039a84736a5083262bfb20db3763dd85e6099b142a"

      def install
        bin.install "helix-wezterm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quantonganh/helix-wezterm/releases/download/v0.0.1/helix-wezterm_Darwin_arm64.tar.gz"
      sha256 "b93c045b047e0bbfea3107111d39d7836e12f4cfc446be3646bea6593c61126f"

      def install
        bin.install "helix-wezterm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/helix-wezterm/releases/download/v0.0.1/helix-wezterm_Linux_x86_64.tar.gz"
      sha256 "d2ce13c5113fb597433825606a3027754cf5a37beaf37aa8c70c1fba9c42b70e"

      def install
        bin.install "helix-wezterm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantonganh/helix-wezterm/releases/download/v0.0.1/helix-wezterm_Linux_arm64.tar.gz"
      sha256 "4b09b27a10544a742da1de531c4f0bb1eaff7b5cdea926ba692610d874096774"

      def install
        bin.install "helix-wezterm"
      end
    end
  end
end
