# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SnippetsLs < Formula
  desc "A simple language server to just insert snippets into Helix."
  homepage "https://github.com/quantonganh/snippets-ls"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/snippets-ls/releases/download/v0.0.1/snippets-ls_Darwin_x86_64.tar.gz"
      sha256 "2735c15f4499cf52f9f16deb37887c2d327b1dd3b346ba8c76f98f4c548291fe"

      def install
        bin.install "snippets-ls"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quantonganh/snippets-ls/releases/download/v0.0.1/snippets-ls_Darwin_arm64.tar.gz"
      sha256 "e2a0463f8cb90e5904def8a8fa7ce9a56b3cbae31163703ce418408a41d2493e"

      def install
        bin.install "snippets-ls"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/snippets-ls/releases/download/v0.0.1/snippets-ls_Linux_x86_64.tar.gz"
      sha256 "cc76042bfa6be194b0802e45b29fa01a82ca81d5678c98925332b68c4cd6e295"

      def install
        bin.install "snippets-ls"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantonganh/snippets-ls/releases/download/v0.0.1/snippets-ls_Linux_arm64.tar.gz"
      sha256 "0524c10d38793a64dfcf55616a211b09c1196e6d8b0dd85c23526413ff70b8bc"

      def install
        bin.install "snippets-ls"
      end
    end
  end
end
