# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TaskwarriorTui < Formula
  desc "A terminal UI for Taskwarrior, written in Go with the tview library."
  homepage "https://github.com/quantonganh/taskwarrior-tui"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/quantonganh/taskwarrior-tui/releases/download/v0.0.1/taskwarrior-tui_Darwin_arm64.tar.gz"
      sha256 "9a3b86ce59e19f679118cd34331ad7ffb688731d1c81cefeac65e0bbf9419a3a"

      def install
        bin.install "taskwarrior-tui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/taskwarrior-tui/releases/download/v0.0.1/taskwarrior-tui_Darwin_x86_64.tar.gz"
      sha256 "ac4fe3335b14c124d00aee44d6aa2d9e55b5a65e422f668141d2b4fcac801e40"

      def install
        bin.install "taskwarrior-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantonganh/taskwarrior-tui/releases/download/v0.0.1/taskwarrior-tui_Linux_arm64.tar.gz"
      sha256 "60a0b3bc330400b9e7885326bd252479056c214c1f15f99aeec088b46ddf87b8"

      def install
        bin.install "taskwarrior-tui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/taskwarrior-tui/releases/download/v0.0.1/taskwarrior-tui_Linux_x86_64.tar.gz"
      sha256 "7eea3e544459a7784930e0cff3bd4a6e7aae255fa3a7b65c892a2ef130ee0d6c"

      def install
        bin.install "taskwarrior-tui"
      end
    end
  end
end
