# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChatgptTui < Formula
  desc "A simple terminal UI for ChatGPT, written in Go with the tview library."
  homepage "https://github.com/quantonganh/chatgpt"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/chatgpt-tui/releases/download/v0.0.7/chatgpt-tui_Darwin_x86_64.tar.gz"
      sha256 "28f7fa4513d3e72924ef143240eb34aeb32b77d2963d4cd2d41e92c7f61d1fde"

      def install
        bin.install "chatgpt-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quantonganh/chatgpt-tui/releases/download/v0.0.7/chatgpt-tui_Darwin_arm64.tar.gz"
      sha256 "defcb9fa11a56130310cb8d53d3d6fa9d14c4c56f961e65fcdce9f1d1c1f0065"

      def install
        bin.install "chatgpt-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantonganh/chatgpt-tui/releases/download/v0.0.7/chatgpt-tui_Linux_arm64.tar.gz"
      sha256 "6ad76905b93bf0346687caae8ff6f1715dc3ae1555e25f9a8969ca892bc8ebf5"

      def install
        bin.install "chatgpt-tui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/chatgpt-tui/releases/download/v0.0.7/chatgpt-tui_Linux_x86_64.tar.gz"
      sha256 "7c795f86a9244f176bc209c2e74ae62b99d51fffbca99b1d949163d003bf4796"

      def install
        bin.install "chatgpt-tui"
      end
    end
  end
end
