# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChatgptTui < Formula
  desc "A simple terminal UI for ChatGPT, written in Go with the tview library."
  homepage "https://github.com/quantonganh/chatgpt"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/quantonganh/chatgpt-tui/releases/download/v0.0.7/chatgpt-tui_Darwin_arm64.tar.gz"
      sha256 "cc4fa1928275ab01e53817ea43bab3313b09ba9dadc5bb965a37b62c725e3275"

      def install
        bin.install "chatgpt-tui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/chatgpt-tui/releases/download/v0.0.7/chatgpt-tui_Darwin_x86_64.tar.gz"
      sha256 "e38f8dedf19d6097def136d69179e3d1814eaed6f0f446c4b86557d747e1bb33"

      def install
        bin.install "chatgpt-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantonganh/chatgpt-tui/releases/download/v0.0.7/chatgpt-tui_Linux_arm64.tar.gz"
      sha256 "c6649f30133ef35056cc2603a1c97982a41fba3009d0e4f929ca660d507fbf5e"

      def install
        bin.install "chatgpt-tui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/chatgpt-tui/releases/download/v0.0.7/chatgpt-tui_Linux_x86_64.tar.gz"
      sha256 "c9b7002f00f47e54da96fb8385ea60beebedf960038b378dc7f12fdb0d131872"

      def install
        bin.install "chatgpt-tui"
      end
    end
  end
end
