# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fe < Formula
  desc "Fuzzy Explorer for everything: logs, configs, Kafka topics, and more."
  homepage "https://github.com/quantonganh/fe"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/fe/releases/download/v0.0.1/fe_Darwin_x86_64.tar.gz"
      sha256 "6d9ab83893db3ff1b446b45c9fac235c8d45a491acce5aeffdca58395b8872f2"

      def install
        bin.install "fe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quantonganh/fe/releases/download/v0.0.1/fe_Darwin_arm64.tar.gz"
      sha256 "7913824bd09ef3d0c91496f0e505f7358fb6d7fb5c6ce671fa48d0af2cfd583a"

      def install
        bin.install "fe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/quantonganh/fe/releases/download/v0.0.1/fe_Linux_x86_64.tar.gz"
        sha256 "3e3289d0b98e1549a333c330c6996ea896269d6594b60ed44ec4ea759eb42f9b"

        def install
          bin.install "fe"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/quantonganh/fe/releases/download/v0.0.1/fe_Linux_arm64.tar.gz"
        sha256 "54e2edd160380ed2d36af89b65f269cf9e4700495b2dcccd84ad3fea1d28792c"

        def install
          bin.install "fe"
        end
      end
    end
  end
end
