# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Geohash < Formula
  desc "Encode and decode Geohashes."
  homepage "https://github.com/quantonganh/geohash"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/geohash/releases/download/v0.0.3/geohash_Darwin_x86_64.tar.gz"
      sha256 "6ef5839b1476357c39b5e90289e5a740cc779068c40facac687b12ea1b82b274"

      def install
        bin.install "geohash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quantonganh/geohash/releases/download/v0.0.3/geohash_Darwin_arm64.tar.gz"
      sha256 "ed4f60f37c0068ca065b72f148778fa49c37ca4a02a4f4fb9d5a7e7cad274061"

      def install
        bin.install "geohash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantonganh/geohash/releases/download/v0.0.3/geohash_Linux_arm64.tar.gz"
      sha256 "4dba467b498e0f5e434bada1c6d7e66db63698b1d27879706d074ad28e68e006"

      def install
        bin.install "geohash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/geohash/releases/download/v0.0.3/geohash_Linux_x86_64.tar.gz"
      sha256 "877a6682b138ac411b63e7c8de15e5e6000bf05f6c1c40f0d8117192460e4664"

      def install
        bin.install "geohash"
      end
    end
  end
end
