# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Geohash < Formula
  desc "Encode and decode Geohashes."
  homepage "https://github.com/quantonganh/geohash"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/quantonganh/geohash/releases/download/v0.0.1/geohash_Darwin_arm64.tar.gz"
      sha256 "2d470fd56e23b6be6194b104c6aac480af58e70c17892d8f25a0e69609dfe3ba"

      def install
        bin.install "geohash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/geohash/releases/download/v0.0.1/geohash_Darwin_x86_64.tar.gz"
      sha256 "4225ed26d0b128e60579ff0a4880561ece5aed58027ba107c006fbcdac416e99"

      def install
        bin.install "geohash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/geohash/releases/download/v0.0.1/geohash_Linux_x86_64.tar.gz"
      sha256 "02af9c1abfa387820a90cf9f7364581a0033e60c21bf11b66eec2c79d8b6ef7b"

      def install
        bin.install "geohash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantonganh/geohash/releases/download/v0.0.1/geohash_Linux_arm64.tar.gz"
      sha256 "c5997cbeaf63da65bd92941ac764b8d46418024cc0b87677f5a02072bbfbc0f2"

      def install
        bin.install "geohash"
      end
    end
  end
end
