# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hdls < Formula
  desc "A simple language server for HDL (nand2tetris)"
  homepage "https://github.com/quantonganh/hdls"
  version "25.09"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/hdls/releases/download/25.09/hdls_25.09_darwin_amd64.tar.gz"
      sha256 "23b4d404119a63213cf98a74262103ce8477eb327a7181090d2b4d10903cf87f"

      def install
        bin.install "hdls"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quantonganh/hdls/releases/download/25.09/hdls_25.09_darwin_arm64.tar.gz"
      sha256 "aae87fd5d56320bd7496aff2ed2f3ae1024d5b6cef2ffc99bb4d6f2b97ee6190"

      def install
        bin.install "hdls"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantonganh/hdls/releases/download/25.09/hdls_25.09_linux_amd64.tar.gz"
      sha256 "5dadc7a585a230276d2e63d8201070f64aba443060057cd314c62e32136dd1b5"
      def install
        bin.install "hdls"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantonganh/hdls/releases/download/25.09/hdls_25.09_linux_arm64.tar.gz"
      sha256 "e4a0e995da843d9c55f68e9c4a51f72a235b8a46b73bf639ecce1b68f8255109"
      def install
        bin.install "hdls"
      end
    end
  end
end
