# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelixWezterm < Formula
  desc "Turning Helix into an IDE with the help of WezTerm and CLI tools"
  homepage "https://github.com/quantonganh/helix-wezterm"
  version "0.0.4"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/quantonganh/helix-wezterm/releases/download/v0.0.4/helix-wezterm_Darwin_arm64.tar.gz"
    sha256 "9415169166837456a896b5abf24e33446936bc83e0daed02772a1861fd77c72a"

    def install
      bin.install "helix-fzf.sh"
      bin.install "helix-wezterm.sh"
    end
  end
end
