# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelixWezterm < Formula
  desc "Turning Helix into an IDE with the help of WezTerm and CLI tools"
  homepage "https://github.com/quantonganh/helix-wezterm"
  version "0.0.5"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/quantonganh/helix-wezterm/releases/download/v0.0.5/helix-wezterm_Darwin_arm64.tar.gz"
    sha256 "663f6e9c73c4f962ad44bf087b765a8856a78fa446928173999266459aa7c278"

    def install
      bin.install "helix-fzf.sh"
      bin.install "helix-wezterm.sh"
    end
  end
end
