# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JdtlsWrapper < Formula
  desc "A Java language server wrapper for Helix editor."
  homepage "https://github.com/quantonganh/jdtls-wrapper"
  version "25.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/jdtls-wrapper/releases/download/25.11/jdtls-wrapper_Darwin_x86_64.tar.gz"
      sha256 "5b14d70ed901561bb2f3a3faf88d986fc0c1ac93a12092d15370f3e1314e9e4d"

      def install
        bin.install "jdtls-wrapper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quantonganh/jdtls-wrapper/releases/download/25.11/jdtls-wrapper_Darwin_arm64.tar.gz"
      sha256 "32275d1aee25ab4728364089d18ef45964b1053cc25446a20395e18b64ff8a3c"

      def install
        bin.install "jdtls-wrapper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantonganh/jdtls-wrapper/releases/download/25.11/jdtls-wrapper_Linux_x86_64.tar.gz"
      sha256 "ed582e7dab4dc4fe14a3833f209b2294abb582ea51c54997ade0206b0d4b1e79"
      def install
        bin.install "jdtls-wrapper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantonganh/jdtls-wrapper/releases/download/25.11/jdtls-wrapper_Linux_arm64.tar.gz"
      sha256 "fc1281f2514d7756c99a851920a94557fdb9fcec42829e19c94f49455b9be219"
      def install
        bin.install "jdtls-wrapper"
      end
    end
  end
end
