# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SnippetsLs < Formula
  desc "A simple language server to just insert snippets into Helix."
  homepage "https://github.com/quantonganh/snippets-ls"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/snippets-ls/releases/download/v0.0.2/snippets-ls_Darwin_x86_64.tar.gz"
      sha256 "d12901ff246f5d9788406a61a1123ede1cf82ace2cfbe6e4d4c58c046ec3eb03"

      def install
        bin.install "snippets-ls"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quantonganh/snippets-ls/releases/download/v0.0.2/snippets-ls_Darwin_arm64.tar.gz"
      sha256 "559c03a02f31e277d6b1d75ed044f677f5fef6d1bb4ac7226536f58d9e144170"

      def install
        bin.install "snippets-ls"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/quantonganh/snippets-ls/releases/download/v0.0.2/snippets-ls_Linux_x86_64.tar.gz"
      sha256 "8e25d687c4a294ec91b7f2ae414096594d2f35e789bdce7c881710f3cc0a073f"

      def install
        bin.install "snippets-ls"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantonganh/snippets-ls/releases/download/v0.0.2/snippets-ls_Linux_arm64.tar.gz"
      sha256 "2483bbb6b0366e74ff0d2741869154423fddbcc9f55aac49ba52f66fd75a05fe"

      def install
        bin.install "snippets-ls"
      end
    end
  end
end
